# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build_book_ja:
    cmds:
      - uv run jupyter-book build docs/ja

  build_book_ja_all:
    cmds:
      - uv run jupyter-book build docs/ja --all

  open_book_ja:
    cmds:
      - uv run python -m webbrowser file:///$(pwd)/docs/ja/_build/html/index.html

  watch_book_ja:
    cmds:
      - fswatch -o docs/ja/**/*.ipynb | xargs -n1 -I{} jupyter-book build docs/ja

  book_ja:
    cmds:
      - task: build_book_ja
      - task: open_book_ja

  book_ja_all:
    cmds:
      - task: build_book_ja_all
      - task: open_book_ja

  build_book_en:
    cmds:
      - uv run jupyter-book build docs/en

  build_book_en_all:
    cmds:
      - uv run jupyter-book build docs/en --all

  open_book_en:
    cmds:
      - uv run python -m webbrowser file:///$(pwd)/docs/en/_build/html/index.html

  watch_book_en:
    cmds:
      - fswatch -o docs/en/**/*.ipynb | xargs -n1 -I{} jupyter-book build docs/en

  book_en:
    cmds:
      - task: build_book_en
      - task: open_book_en

  book_en_all:
    cmds:
      - task: build_book_en_all
      - task: open_book_en
