# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build_book_ja:
    desc: Build the Japanese version of the book
    cmds:
      - uv run jupyter-book build docs/ja

  build_book_ja_all:
    desc: Build the Japanese version of the book (force rebuild all notebooks)
    cmds:
      - uv run jupyter-book build docs/ja --all

  open_book_ja:
    desc: Open the Japanese version of the book
    cmds:
      - uv run python -m webbrowser file:///$(pwd)/docs/ja/_build/html/index.html

  watch_book_ja:
    desc: Watch Japanese notebooks and auto-rebuild of the book
    cmds:
      - fswatch -o docs/ja/**/*.ipynb | xargs -n1 -I{} jupyter-book build docs/ja

  book_ja:
    desc: Build and open the Japanese version of the book
    cmds:
      - task: build_book_ja
      - task: open_book_ja

  book_ja_all:
    desc: Build and open the Japanese version of the book (force rebuild all notebooks)
    cmds:
      - task: build_book_ja_all
      - task: open_book_ja

  check_book_ja:
    desc: Confirm that the Japanese version of the book builds without errors or warnings
    cmds:
      - uv run jupyter-book build docs/ja --all --warningiserror

  build_book_en:
    desc: Build the English version of the book
    cmds:
      - uv run jupyter-book build docs/en

  build_book_en_all:
    desc: Build the English version of the book (force rebuild all notebooks)
    cmds:
      - uv run jupyter-book build docs/en --all

  open_book_en:
    desc: Open the English version of the book
    cmds:
      - uv run python -m webbrowser file:///$(pwd)/docs/en/_build/html/index.html

  watch_book_en:
    desc: Watch English notebooks and auto-rebuild of the book
    cmds:
      - fswatch -o docs/en/**/*.ipynb | xargs -n1 -I{} jupyter-book build docs/en

  book_en:
    desc: Build and open the English version of the book
    cmds:
      - task: build_book_en
      - task: open_book_en

  book_en_all:
    desc: Build and open the English version of the book (force rebuild all notebooks)
    cmds:
      - task: build_book_en_all
      - task: open_book_en

  check_book_en:
    desc: Confirm that the English version of the book builds without errors or warnings
    cmds:
      - uv run jupyter-book build docs/en --all --warningiserror

  create_release_note:
    desc: Create release notes for the specified version
    cmds:
      - cp ./templates/release_note_en.ipynb ./docs/en/releases/jijmodeling-{{.CLI_ARGS}}.ipynb
      - cp ./templates/release_note_ja.ipynb ./docs/ja/releases/jijmodeling-{{.CLI_ARGS}}.ipynb
      - 'yq -i ''.parts[-1].chapters |= [{"file": "releases/jijmodeling-{{.CLI_ARGS}}"}] + .'' docs/ja/_toc.yml'
      - 'yq -i ''.parts[-1].chapters |= [{"file": "releases/jijmodeling-{{.CLI_ARGS}}"}] + .'' docs/en/_toc.yml'

  sync_paired_notebooks:
    desc: Synchronize paired notebooks and markdown files
    cmds:
      - find docs -name "*.ipynb" -not -path "*/_build/*" -exec uv run jupytext --sync {} \;

  check_paired_notebooks:
    desc: Check that all notebooks and markdown files are properly paired and synchronized
    cmds:
      - |
        #!/bin/bash
        # Check for the existence of corresponding Notebook/Markdown files
        NOTEBOOKS=$(find docs -name "*.ipynb" -not -path "*/_build/*")
        DOCS=$(echo "$NOTEBOOKS" | sed 's|^docs/||; s|.ipynb$||' | sort)
        MDS=$(find markdowns -name "*.md" | sed 's|^markdowns/||; s|.md$||' | sort)
        DIFF=$(diff <(echo "$DOCS") <(echo "$MDS")) || true
        if [ -n "$DIFF" ]; then
          echo "[FAILED] The following notebooks/md files are not paired:"
          echo "$DIFF"
          exit 1
        fi
        # Check for the synchronization between Notebooks and Markdown files
        ERR=0;
        while read -r TARG; do
          LOG=$(uv run jupytext --pre-commit-mode --show-changes --sync $TARG) || true;
          if grep -q "Error:" <<< "$LOG"; then
            echo "$LOG"
            ERR=1
          fi
        done <<< "$NOTEBOOKS";
        if [ $ERR -ne 0 ]; then
          echo "[FAILED] The notebooks/markdowns are not syncrhonized.";
          exit 1;
        fi
        echo "[SUCCESS] All notebooks/markdowns are properly paired and synchronized.";
