version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - python -c "import jijmodeling, os; print('JijModeling path:', os.path.dirname(jijmodeling.__file__))"
      - sphinx-apidoc -o apidocs/ --force --separate $(python -c "import jijmodeling, os; print(os.path.dirname(jijmodeling.__file__))")

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py

formats: ["htmlzip", "pdf", "epub"]
