version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - python -c "import jijmodeling, os, subprocess; jm_path = os.path.dirname(jijmodeling.__file__); print('JijModeling path:', jm_path); subprocess.call(['sphinx-apidoc', '-o', 'apidocs/', '--force', '--separate', jm_path])"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py

formats: ["htmlzip", "pdf", "epub"]
