version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - python -c "import jijmodeling, subprocess, os; subprocess.call(['sphinx-apidoc', '-o', 'apidocs/', '--force', '--separate', os.path.dirname(jijmodeling.__file__)])"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py

formats: ["htmlzip", "pdf", "epub"]
