version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - |
        JM_PATH=$(python -c "import jijmodeling, os; print(os.path.dirname(jijmodeling.__file__))")
        echo "JijModeling path: $JM_PATH"
        sphinx-apidoc -o apidocs/ --force --separate "$JM_PATH"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py

formats: ["htmlzip", "pdf", "epub"]
