version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: reference/requirements.txt

sphinx:
  configuration: reference/conf.py

formats: ["htmlzip", "pdf", "epub"]
